### ISSUE TITLE
About how to process LUP dataset

### ISSUE THREAD

**Issue by whobefore** [michuanhaohao/TransReID-SSL#1]
Excellent work! And how you process dets.pkl of LUP dataset? It seems that the video extraction has resolution problem and we don't know the FPS. If you have done it, could you send me the script? Thanks a lot!

**Comment by YanzuoLu** [comment]
@whobefore Hi! I'm confused by the same problem. Have you successfully extract proper crops from different resolution of the videos?

**Comment by whobefore** [comment]
Actually, I did not solve this problem completely. It seems that LUP use 360p video, but there still exists some wrongly predicted boxes.
