### ISSUE TITLE
有关Youtube视频清晰度的问题

### ISSUE THREAD

**Issue by YanzuoLu** [michuanhaohao/TransReID-SSL#2]
请问下预训练使用的LUPerson数据集在下载时视频清晰度问题是怎么解决的呢？还是说通过CFS筛掉了呢，没有统一的提取脚本实在是很难复现结果orz

**Comment by YanzuoLu** [comment]
统计了一下每段视频bbox出现的最高height，720p:480p:360p的比例在5:1:3左右，但按这种方法提取出来的数据就可能比较...

**Comment by michuanhaohao** [comment]
同学你好，数据集可以找LUPerson一作或者通讯帮忙获取~
