### ISSUE TITLE
Pre-trained Models

### ISSUE THREAD

**Issue by wengdunfang** [michuanhaohao/TransReID-SSL#4]
Hi, can you provide pre-trained model weights of MoCo and MoBy on LUPerson dataset?

**Comment by michuanhaohao** [comment]
Sorry, the open-source model requires strict approval from the company, so we can not upload Moco and Moby pre-trained models. You can use the original repos to pre-train the models. We used the default training settings.

**Comment by wengdunfang** [comment]
> Sorry, the open-source model requires strict approval from the company, so we can not upload Moco and Moby pre-trained models. You can use the original repos to pre-train the models. We used the default training settings.

ok, Thanks for your reply.
In MoCoV3, the batch size equal to 1024 ?

**Comment by michuanhaohao** [comment]
> > Sorry, the open-source model requires strict approval from the company, so we can not upload Moco and Moby pre-trained models. You can use the original repos to pre-train the models. We used the default training settings.
> 
> ok, Thanks for your reply. In MoCoV3, the batch size equal to 1024 ?

Yes. Here are training settings (image size=256*128). 
```
python main_moco.py \
  -a vit_small -b 1024 \
  --optimizer=adamw --lr=1.5e-4 --weight-decay=.1 \
  --epochs=300 --warmup-epochs=40 \
  --stop-grad-conv1 --moco-m-cos --moco-t=.2 \
  --data ./datasets/LUP  \
```

**Comment by wengdunfang** [comment]
thank you
