### ISSUE TITLE
Performance on Domain Generalization

### ISSUE THREAD

**Issue by liyuke65535** [michuanhaohao/TransReID-SSL#6]
Thanks for your works on ReID! I got several questions: 
1. I see you've done UDA experiments between market and msmt in TransReID-SSL. What if just train the model on A person-dataset then test on B person-dataset? How's the performance?  
2. What does 'patchify stem' mean? More specifically, what's the purpose of ICS component and where it works?

**Comment by liyuke65535** [comment]
Looking forward to your generous help!

**Comment by michuanhaohao** [comment]
1. You can evaluate the open-sourced models on B dataset. I consider it may be better than the baseline.
2. 'patchify stem' means the 16*16 Conv2D layer before Transformer Blocks.
