### ISSUE TITLE
请问使用LUPerson进行pretrain时，LUPerson的数据集文件结构是什么样的？

### ISSUE THREAD

**Issue by siyuch-fdu** [michuanhaohao/TransReID-SSL#7]
非常感谢您的工作！
我想使用您的DINO代码对LUPerson进行预训练，我看到您的代码好像是将LUPerson里边的数据以图片的形式直接load（main_dino.py line153: `dataset = datasets.ImageFolder(args.data_path, transform=transform)`）。但是我拿到的LUPerson数据集是.mdb格式的，没办法直接读取。想问下我是否需要将.mdb格式的数据集转换成.jpg图片？如果需要的话，转换后的LUPerson数据集的组织形式是什么样的？（从main_dino.py line158: `dir_path = os.path.join(args.data_path,'images')` 看到似乎LUPerson文件夹下还有‘images’文件夹）

希望您能帮助我解决这个问题，万分感谢！

**Comment by michuanhaohao** [comment]
参考mdb格式的解码代码解码成RGB图像，然后存成jpg图像

**Comment by siyuch-fdu** [comment]
感谢您的回复~这个问题已经解决了
